/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1--fTxyBfY-8Ziuqh4-g7Txo16CrOe2FA5SEZ1VSd5tXJlPUHp-MmLhVfhv0IVC-wL9yS6dGlJJTwHTqrifihRZjo2a6Z6rFbQ29wsSwQiIR2UjxhcTHghbscc",
  "tt": "tt-1-rB9ZqV7SF3yO5fCwAc-s-i1cPOw1fqbzESEjG4x00qI=",
  "version": "2020-11-20"
}

export default ebconfig;